name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set image version (tag)
        id: image_version
        run: echo "gitsha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/anwarmaswadeh/express-docker:${{ steps.image_version.outputs.gitsha }}
      - name: publish the Docker image
        run: docker push ghcr.io/anwarmaswadeh/express-docker:${{ steps.image_version.outputs.gitsha }} 
      - name: configure docker host
        uses: khaledez/configure-docker-host@v1
        with:
          host: i-0eb54b0f519f46164
          user: github
          ssh-private-key: ${{ secrets.DEPLOYMENT_KEY }}
      - name: deploy
        run: docker compose -f docker-compose-prod.yml up -d
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
     - name: print logs
       if: always()
       run: docker compose logs      